db:
    container_name: db
    image: mysql:5.7
    ports:
        - "3306:3306"
    environment:
        - "MYSQL_ROOT_PASSWORD=root"
        - "MYSQL_USER=yams"
        - "MYSQL_PASSWORD=yams"
        - "MYSQL_DATABASE=yams"
web:
    image: juju/web
    container_name: web
    environment:
      - "USER_ID=${USER_ID}"
      - "GROUP_ID=${GROUP_ID}"
    links:
        - db
    ports:
        - 8080:80
        - "9000:80"
    volumes:
        - .:/var/www/yams

elk:
    container_name: elk
    image: willdurand/elk
    ports:
        - 81:80
    volumes:
        - ../docker/elk/logstash:/etc/logstash
        - ../docker/elk/logstash/patterns:/opt/logstash/patterns
    volumes_from:
        - web